# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
#
# EDIT THESE As required
#
comments: true
owner_name: YOUR_NAME # Change this to your name
email: YOUR_EMAIL # Change this to your email
twitter_username: YOUR_TWITTER_USERNAME # Change this to your username
github_username:  YOUR_GITHUB_USERNAME # Change this to your user name
# URLS used in the docs will always start with a slash
#  URL variables should, therefore, NEVER end with a slash character
url: https://docsbydesign.github.io # your URL should look like https://<YOUR_ACCOUNT>/github.io
#
# These properties should be OK the way they are.
#
title: TC Myths TEST # DO NOT CHANGE THIS
lang: en-US # Leave this as English for now
description: All technical communication myths in place.
baseurl: /tcmyths # the subpath of your site, it should be OK as it is
mybaseurl: /tcmyths # defined to have a base url variable that isn't used for something else by Jekyll, it should be OK as it is
#
#	These collections contain the site content
#		myths contains the myth topics
#		refs contains the source reference topics
#
collections:
  myths:
    output: true
  refs:
    output: true
author:
  name: Bob Watson
  url: https://docsbydesign.com

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
