# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TC Myths
owner_name: Bob Watson
email: tcmyths@tcmyths.com
lang: en-US
description: All the common technical communication myths in place.
# URLS used in the docs will always start with a slash
#  URL variables should, therefore, NEVER end with a slash character
url: https://tcmyths.github.io # the base hostname & protocol for your site
baseurl: /tcmyths # the subpath of your site, e.g. /blog
mybaseurl: /tcmyths # defined to have a base url variable that isn't used for something else by Jekyll
twitter_username: bobwatsonphd
github_username:  tcmyths
include: ['pages']
google_analytics: UA-58134115-2
author:
  name: Bob Watson
  url: https://docsbydesign.com

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
