# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TC Myths TEST
owner_name: Bob Watson
email: tcmyths@docsbydesign.com
lang: en-US
description: All the technical communication myths in place.
# URLS used in the docs will always start with a slash
#  URL variables should, therefore, NEVER end with a slash character
url: https://docsbydesign.github.io # your URL should look like https://<YOUR_ACCOUNT>/github.io
baseurl: /tcmyths # the subpath of your site, e.g. /blog
mybaseurl: /tcmyths # defined to have a base url variable that isn't used for something else by Jekyll
twitter_username: bobwatsonphd
github_username:  tcmyths
collections:
  myths:
    output: true
  refs:
    output: true
# include: ['myths','refs']
author:
  name: Bob Watson
  url: https://docsbydesign.com

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
